services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    environment:
      - TZ=America/Mexico_City
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro

  backend:
    build:
      context: ./Backend
    container_name: backend_app
    restart: always
    env_file:
      - .env
    environment:
      - TZ=America/Mexico_City
    volumes:
      - ./session:/auth
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    command: ["yarn", "start"]

  frontend:
    build:
      context: ./Frontend
    container_name: frontend_app
    restart: always
    environment:
      - TZ=America/Mexico_City
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    depends_on:
      - backend

volumes:
  mysql_data:
